### ISSUE TITLE
Errors loading website 

### ISSUE THREAD

**Issue by qaxim** [travelpayouts/flights-api-project#5]
Hi team 

I have done all the steps but my site loading with errors 
please suggest how to fix : 

An Error occurred while handling another error:
Exception: It seems that you are forgot to compile your frontend files with webpack. Check documentation at https://github.com/travelpayouts/flights-api-project in /home/phpnet/public_html/public/tp/travel/components/WebpackAssetBundle.php:65
Stack trace:
#0 /home/phpnet/public_html/public/tp/travel/components/WebpackAssetBundle.php(23): app\components\WebpackAssetBundle->getWebpackAssets()
#1 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/base/BaseObject.php(109): app\components\WebpackAssetBundle->init()
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/di/Container.php(376): ReflectionClass->newInstanceArgs(Array)
#4 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('app\\assets\\AppA...', Array, Array)
#5 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('app\\assets\\AppA...', Array, Array)
#6 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/web/AssetManager.php(264): yii\BaseYii::createObject(Array)
#7 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/web/AssetManager.php(237): yii\web\AssetManager->loadBundle('app\\assets\\AppA...', Array, true)
#8 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/web/View.php(286): yii\web\AssetManager->getBundle('app\\assets\\AppA...')
#9 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/web/AssetBundle.php(125): yii\web\View->registerAssetBundle('app\\assets\\AppA...')
#10 /home/phpnet/public_html/public/tp/travel/views/layouts/main.php(10): yii\web\AssetBundle::register(Object(yii\web\View))
#11 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/base/View.php(348): require('/home/phpnet/pu...')
#12 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/phpnet/pu...', Array)
#13 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/home/phpnet/pu...', Array, Object(app\controllers\SiteController))
#14 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#15 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#16 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#17 [internal function]: yii\web\ErrorAction->run()
#18 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#19 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array)
#20 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('error', Array)
#21 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/web/ErrorHandler.php(108): yii\base\Module->runAction('site/error')
#22 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#23 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#24 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "public/tp/travel/web/". in /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/base/Module.php:537
Stack trace:
#0 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('public/tp/trave...', Array)
#1 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /home/phpnet/public_html/public/tp/travel/web/index.php(13): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /home/phpnet/public_html/public/tp/travel/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /home/phpnet/public_html/public/tp/travel/web/index.php(13): yii\base\Application->run()
#2 {main}

**Comment by magbaba** [comment]
Any updates on this? We are getting the same error. @qaxim did you find a fix?

**Comment by versatilegurung** [comment]
> Any updates on this? We are getting the same error. @qaxim did you find a fix?

Did you manage to solve this issue?

**Comment by versatilegurung** [comment]
http://ticket2ktm.com/flights-api/

**Comment by qaxim** [comment]
no its not fixed Im still looking for solution :(

**Comment by Boby** [comment]
still not fixed? having the same issues where it complains about webpack installations, but I did the webpack installations and new error come up when we run the : webpack -w

the error : 
webpack.config.babel.js:4

> import path from 'path';
>        ^^^^
> 
> SyntaxError: Unexpected identifier
>     at new Script (vm.js:83:7)

**Comment by koziejakub** [comment]
Follow the instructions to install this. Unfortunately, when I upload to the server I get a bug that looks like I forgot to compile the files - follow the instructions and still does not work. How do I solve this?

**Comment by tpsupport** [comment]
Hi, @koziejakub! Could you please send us an email to support@travelpayouts.com with the detailed description how you install this template with the screenshot of this error?

**Comment by koziejakub** [comment]
> Cześć @koziejakub ! Czy możesz wysłać nam wiadomość e-mail na [adres support@travelpayouts.com](mailto:support@travelpayouts.com) ze szczegółowym opisem instalacji tego szablonu ze zrzutem ekranu przedstawiającym ten błąd?

I sent an e-mail.

**Comment by landman** [comment]
I still have the same problem. "It seems that you are forgot to compile your frontend files with webpack."

**Comment by tpsupport** [comment]
Hello, Dennis! Could you please provide us the error messages you get together with your XAMPP configuration settings at  support@travelpayouts.com? We will have a look into the issue.
